import type { ContentFormatRecipe } from '../schemas/contentFormat.schema.js';

/**
 * The 50 content format recipes.
 *
 * Each format is a structured recipe that the AI orchestrator feeds into every
 * generation step: hook style, pacing, visual treatment, caption styling,
 * narration tone, scene structure, CTA approach, and loop strategy.
 */
export const CONTENT_FORMATS: readonly ContentFormatRecipe[] = [
  // ─── Storytelling ───────────────────────────────────────────────────
  {
    id: 'brainrot',
    name: 'Brainrot',
    category: 'entertainment',
    description: 'Absurd, fast-paced content with unexpected visuals, escalating chaos, and loop endings that keep viewers watching.',
    recommendedDuration: { min: 15, max: 30, default: 20 },
    pacing: 'very-fast',
    hookStyles: ['shock', 'curiosity', 'bold-claim'],
    structure: [
      { label: 'Absurd Premise', description: 'Drop the viewer into an unexpected situation', weight: 1 },
      { label: 'Escalation', description: 'Things get increasingly ridiculous', weight: 2 },
      { label: 'Peak Absurdity', description: 'Maximum chaos moment', weight: 2 },
      { label: 'Loop Ending', description: 'End connects back to start seamlessly', weight: 1 },
    ],
    visualStyle: 'dynamic',
    captionStyle: 'bold-center',
    narrationStyle: 'energetic',
    sceneDuration: { min: 1, max: 5, default: 3 },
    ctaStyles: ['loop', 'share'],
    loopStrategy: 'hard-loop',
    musicIntensity: 0.8,
    transitions: ['zoom-cut', 'whip-pan', 'glitch'],
    audienceTriggers: ['confusion', 'humor', 'surprise', 'absurdity'],
  },
  {
    id: 'pov',
    name: 'POV',
    category: 'storytelling',
    description: 'First-person immersive scenarios that put the viewer directly into the situation.',
    recommendedDuration: { min: 15, max: 45, default: 25 },
    pacing: 'moderate',
    hookStyles: ['pov', 'story', 'emotional'],
    structure: [
      { label: 'Situation', description: 'Establish the POV scenario immediately', weight: 1 },
      { label: 'Immersion', description: 'Deepen the first-person experience', weight: 2 },
      { label: 'Escalation', description: 'Raise the stakes or intensity', weight: 2 },
      { label: 'Payoff', description: 'Deliver the emotional or comedic resolution', weight: 1.5 },
    ],
    visualStyle: 'cinematic',
    captionStyle: 'phrase',
    narrationStyle: 'conversational',
    sceneDuration: { min: 3, max: 12, default: 6 },
    ctaStyles: ['comment', 'follow'],
    loopStrategy: 'none',
    musicIntensity: 0.4,
    transitions: ['cut', 'dissolve'],
    audienceTriggers: ['relatability', 'empathy', 'immersion'],
  },
  {
    id: 'storytime',
    name: 'Storytime',
    category: 'storytelling',
    description: 'Personal narrative format with a clear beginning, middle, and end. The creator tells a story from their experience.',
    recommendedDuration: { min: 30, max: 45, default: 35 },
    pacing: 'moderate',
    hookStyles: ['story', 'shock', 'curiosity'],
    structure: [
      { label: 'Hook', description: 'The most dramatic or intriguing moment teased', weight: 1 },
      { label: 'Context', description: 'Set the scene and characters', weight: 1.5 },
      { label: 'Rising Action', description: 'Build toward the key moment', weight: 2.5 },
      { label: 'Climax', description: 'The pivotal moment of the story', weight: 2 },
      { label: 'Resolution', description: 'Wrap up and reflect', weight: 1 },
    ],
    visualStyle: 'talking-head',
    captionStyle: 'word-by-word',
    narrationStyle: 'storytelling',
    sceneDuration: { min: 4, max: 12, default: 7 },
    ctaStyles: ['follow', 'comment'],
    loopStrategy: 'none',
    musicIntensity: 0.3,
    transitions: ['cut', 'cross-dissolve'],
    audienceTriggers: ['curiosity', 'empathy', 'drama', 'relatability'],
  },
  {
    id: 'mystery',
    name: 'Mystery',
    category: 'storytelling',
    description: 'Unfold a mystery with clues, building suspense, and a twist reveal at the end.',
    recommendedDuration: { min: 25, max: 45, default: 35 },
    pacing: 'slow',
    hookStyles: ['mystery', 'question', 'curiosity'],
    structure: [
      { label: 'Question', description: 'Pose the central mystery', weight: 1.5 },
      { label: 'Context', description: 'Background needed to understand the mystery', weight: 1.5 },
      { label: 'Clue 1', description: 'First piece of evidence', weight: 2 },
      { label: 'Clue 2', description: 'Second piece that deepens or redirects', weight: 2 },
      { label: 'Twist', description: 'Unexpected turn in understanding', weight: 2 },
      { label: 'Reveal', description: 'The answer or open ending', weight: 1.5 },
    ],
    visualStyle: 'cinematic',
    captionStyle: 'subtitle',
    narrationStyle: 'dramatic',
    sceneDuration: { min: 4, max: 10, default: 6 },
    ctaStyles: ['comment', 'follow'],
    loopStrategy: 'soft-loop',
    musicIntensity: 0.5,
    transitions: ['dissolve', 'fade', 'cut'],
    audienceTriggers: ['curiosity', 'suspense', 'surprise', 'intrigue'],
  },
  {
    id: 'dark-stories',
    name: 'Dark Stories',
    category: 'storytelling',
    description: 'Unsettling narratives with eerie atmosphere, ominous tone, and chilling conclusions.',
    recommendedDuration: { min: 25, max: 45, default: 35 },
    pacing: 'slow',
    hookStyles: ['shock', 'mystery', 'story'],
    structure: [
      { label: 'Hook', description: 'Chilling opening that sets the tone', weight: 1.5 },
      { label: 'Setting', description: 'Establish the eerie world', weight: 2 },
      { label: 'Build', description: 'Escalating unease and tension', weight: 2.5 },
      { label: 'Dark Reveal', description: 'The disturbing truth or twist', weight: 2 },
      { label: 'Lingering', description: 'Leave the viewer with an unsettling thought', weight: 1 },
    ],
    visualStyle: 'cinematic',
    captionStyle: 'subtitle',
    narrationStyle: 'dramatic',
    sceneDuration: { min: 5, max: 12, default: 7 },
    ctaStyles: ['follow', 'series-tease'],
    loopStrategy: 'soft-loop',
    musicIntensity: 0.6,
    transitions: ['fade', 'dissolve', 'cut'],
    audienceTriggers: ['fear', 'curiosity', 'suspense', 'unease'],
  },
  {
    id: 'true-crime',
    name: 'True Crime',
    category: 'storytelling',
    description: 'Factual crime narratives with evidence presentation, timeline reconstruction, and case analysis.',
    recommendedDuration: { min: 30, max: 45, default: 40 },
    pacing: 'moderate',
    hookStyles: ['shock', 'mystery', 'story'],
    structure: [
      { label: 'The Crime', description: 'What happened, stated directly', weight: 1.5 },
      { label: 'The Victim', description: 'Human context and stakes', weight: 1.5 },
      { label: 'Investigation', description: 'Key evidence and leads', weight: 2.5 },
      { label: 'Suspect', description: 'Who and why', weight: 2 },
      { label: 'Resolution', description: 'Outcome and reflection', weight: 1.5 },
    ],
    visualStyle: 'b-roll',
    captionStyle: 'subtitle',
    narrationStyle: 'authoritative',
    sceneDuration: { min: 5, max: 12, default: 8 },
    ctaStyles: ['follow', 'comment', 'series-tease'],
    loopStrategy: 'none',
    musicIntensity: 0.5,
    transitions: ['cut', 'dissolve', 'fade'],
    audienceTriggers: ['curiosity', 'justice', 'morality', 'mystery'],
  },
  {
    id: 'reddit-stories',
    name: 'Reddit Stories',
    category: 'storytelling',
    description: 'First-person internet stories with conversational delivery, dramatic readings, and relatable situations.',
    recommendedDuration: { min: 30, max: 45, default: 35 },
    pacing: 'moderate',
    hookStyles: ['story', 'shock', 'curiosity'],
    structure: [
      { label: 'Setup', description: 'Context for the situation', weight: 1.5 },
      { label: 'Conflict', description: 'The core problem or drama', weight: 2.5 },
      { label: 'Escalation', description: 'Things get more complicated', weight: 2 },
      { label: 'Climax', description: 'The dramatic peak', weight: 2 },
      { label: 'Resolution', description: 'How it ended + reaction', weight: 1 },
    ],
    visualStyle: 'mixed-media',
    captionStyle: 'word-by-word',
    narrationStyle: 'conversational',
    sceneDuration: { min: 4, max: 10, default: 7 },
    ctaStyles: ['comment', 'follow'],
    loopStrategy: 'none',
    musicIntensity: 0.3,
    transitions: ['cut'],
    audienceTriggers: ['drama', 'relatability', 'curiosity', 'outrage'],
  },
  {
    id: 'confession-stories',
    name: 'Confession Stories',
    category: 'storytelling',
    description: 'Personal confessions and secret reveals with emotional weight and moral complexity.',
    recommendedDuration: { min: 25, max: 45, default: 30 },
    pacing: 'moderate',
    hookStyles: ['shock', 'emotional', 'story'],
    structure: [
      { label: 'Confession Hook', description: 'Bold admission that hooks immediately', weight: 1.5 },
      { label: 'Context', description: 'What led to this moment', weight: 2 },
      { label: 'The Act', description: 'What was done or discovered', weight: 2 },
      { label: 'Consequence', description: 'Impact and fallout', weight: 2 },
      { label: 'Reflection', description: 'What it means now', weight: 1.5 },
    ],
    visualStyle: 'talking-head',
    captionStyle: 'word-by-word',
    narrationStyle: 'conversational',
    sceneDuration: { min: 4, max: 10, default: 6 },
    ctaStyles: ['comment', 'follow'],
    loopStrategy: 'none',
    musicIntensity: 0.3,
    transitions: ['cut', 'dissolve'],
    audienceTriggers: ['secrets', 'guilt', 'relatability', 'empathy'],
  },
  {
    id: 'relationship-stories',
    name: 'Relationship Stories',
    category: 'storytelling',
    description: 'Dating and relationship narratives with emotional hooks, conflict, and resolution or lessons.',
    recommendedDuration: { min: 25, max: 45, default: 30 },
    pacing: 'moderate',
    hookStyles: ['story', 'emotional', 'curiosity'],
    structure: [
      { label: 'The Meeting', description: 'How it started', weight: 1.5 },
      { label: 'The Connection', description: 'What drew them together', weight: 2 },
      { label: 'The Problem', description: 'What went wrong', weight: 2.5 },
      { label: 'The Turning Point', description: 'Decision or discovery', weight: 2 },
      { label: 'The Lesson', description: 'What was learned', weight: 1 },
    ],
    visualStyle: 'cinematic',
    captionStyle: 'phrase',
    narrationStyle: 'storytelling',
    sceneDuration: { min: 4, max: 10, default: 6 },
    ctaStyles: ['comment', 'share'],
    loopStrategy: 'none',
    musicIntensity: 0.4,
    transitions: ['cut', 'dissolve'],
    audienceTriggers: ['love', 'heartbreak', 'relatability', 'advice'],
  },
  {
    id: 'aita-stories',
    name: 'AITA Stories',
    category: 'storytelling',
    description: 'Am I The Asshole format with moral dilemmas, multiple perspectives, and audience judgment.',
    recommendedDuration: { min: 25, max: 45, default: 35 },
    pacing: 'moderate',
    hookStyles: ['question', 'story', 'contrarian'],
    structure: [
      { label: 'The Situation', description: 'Set up the moral dilemma', weight: 2 },
      { label: 'My Action', description: 'What the narrator did', weight: 2 },
      { label: 'The Reaction', description: 'How others responded', weight: 2 },
      { label: 'The Defense', description: 'Why it might be justified', weight: 1.5 },
      { label: 'The Question', description: 'Am I the asshole?', weight: 1.5 },
    ],
    visualStyle: 'talking-head',
    captionStyle: 'word-by-word',
    narrationStyle: 'conversational',
    sceneDuration: { min: 5, max: 10, default: 7 },
    ctaStyles: ['comment', 'follow'],
    loopStrategy: 'none',
    musicIntensity: 0.2,
    transitions: ['cut'],
    audienceTriggers: ['judgment', 'morality', 'conflict', 'opinions'],
  },
  // ─── Lifestyle ──────────────────────────────────────────────────────
  {
    id: 'celebrity-stories',
    name: 'Celebrity Stories',
    category: 'lifestyle',
    description: 'Celebrity news, drama, or behind-the-scenes stories with engaging narrative delivery.',
    recommendedDuration: { min: 25, max: 45, default: 30 },
    pacing: 'fast',
    hookStyles: ['shock', 'curiosity', 'story'],
    structure: [
      { label: 'The News', description: 'What happened with the celebrity', weight: 2 },
      { label: 'Background', description: 'Context about who and why it matters', weight: 2 },
      { label: 'Details', description: 'Key facts and timeline', weight: 2.5 },
      { label: 'Impact', description: 'What this means', weight: 1.5 },
      { label: 'Reaction', description: 'Public or expert response', weight: 1 },
    ],
    visualStyle: 'b-roll',
    captionStyle: 'bold-center',
    narrationStyle: 'energetic',
    sceneDuration: { min: 4, max: 10, default: 6 },
    ctaStyles: ['comment', 'follow'],
    loopStrategy: 'none',
    musicIntensity: 0.5,
    transitions: ['cut', 'whip-pan'],
    audienceTriggers: ['fame', 'drama', 'curiosity', 'gossip'],
  },
  {
    id: 'rich-lifestyle',
    name: 'Rich Lifestyle',
    category: 'lifestyle',
    description: 'Aspirational content showcasing luxury, wealth, and expensive things with awe-inspiring visuals.',
    recommendedDuration: { min: 15, max: 30, default: 22 },
    pacing: 'moderate',
    hookStyles: ['shock', 'statistic', 'curiosity'],
    structure: [
      { label: 'The Price', description: 'Lead with the jaw-dropping cost', weight: 1.5 },
      { label: 'The Item', description: 'What makes it special', weight: 2 },
      { label: 'The Details', description: 'Craftsmanship and exclusivity', weight: 2 },
      { label: 'The Lifestyle', description: 'Who owns this and why', weight: 1.5 },
    ],
    visualStyle: 'cinematic',
    captionStyle: 'bold-center',
    narrationStyle: 'authoritative',
    sceneDuration: { min: 3, max: 8, default: 5 },
    ctaStyles: ['follow', 'comment'],
    loopStrategy: 'soft-loop',
    musicIntensity: 0.5,
    transitions: ['dissolve', 'cut'],
    audienceTriggers: ['aspiration', 'awe', 'envy', 'luxury'],
  },
  {
    id: 'luxury-things',
    name: 'Luxury / Expensive Things',
    category: 'lifestyle',
    description: 'Showcase of the most expensive items, experiences, and extravagances with visual emphasis on quality.',
    recommendedDuration: { min: 20, max: 35, default: 25 },
    pacing: 'moderate',
    hookStyles: ['statistic', 'shock', 'listicle'],
    structure: [
      { label: 'The Hook', description: 'The most shocking price or fact', weight: 1.5 },
      { label: 'The Item', description: 'Detailed look at the luxury item', weight: 2.5 },
      { label: 'The Story', description: 'Why it costs so much', weight: 2 },
      { label: 'The Reveal', description: 'Who buys this and what for', weight: 1.5 },
    ],
    visualStyle: 'cinematic',
    captionStyle: 'minimal',
    narrationStyle: 'authoritative',
    sceneDuration: { min: 4, max: 10, default: 6 },
    ctaStyles: ['follow', 'share'],
    loopStrategy: 'none',
    musicIntensity: 0.4,
    transitions: ['dissolve', 'cut'],
    audienceTriggers: ['luxury', 'awe', 'curiosity', 'aspiration'],
  },
  {
    id: 'success-stories',
    name: 'Success Stories',
    category: 'lifestyle',
    description: 'Inspirational narratives about people who achieved remarkable things, with actionable takeaways.',
    recommendedDuration: { min: 30, max: 45, default: 35 },
    pacing: 'moderate',
    hookStyles: ['story', 'statistic', 'bold-claim'],
    structure: [
      { label: 'The Result', description: 'Start with where they ended up', weight: 1.5 },
      { label: 'The Origin', description: 'Where they started', weight: 2 },
      { label: 'The Struggle', description: 'Obstacles and failures', weight: 2.5 },
      { label: 'The Breakthrough', description: 'The key moment or decision', weight: 2 },
      { label: 'The Lesson', description: 'What we can learn', weight: 1 },
    ],
    visualStyle: 'b-roll',
    captionStyle: 'phrase',
    narrationStyle: 'storytelling',
    sceneDuration: { min: 5, max: 12, default: 7 },
    ctaStyles: ['save', 'follow'],
    loopStrategy: 'none',
    musicIntensity: 0.4,
    transitions: ['cut', 'dissolve'],
    audienceTriggers: ['inspiration', 'motivation', 'aspiration', 'hope'],
  },
  {
    id: 'transformation',
    name: 'Transformation',
    category: 'lifestyle',
    description: 'Before/after format showing dramatic changes with visual proof and process explanation.',
    recommendedDuration: { min: 20, max: 40, default: 30 },
    pacing: 'moderate',
    hookStyles: ['shock', 'promise', 'story'],
    structure: [
      { label: 'Before', description: 'Show the starting state dramatically', weight: 1.5 },
      { label: 'Problem', description: 'What needed to change', weight: 1.5 },
      { label: 'Process', description: 'The transformation journey', weight: 3 },
      { label: 'Progress', description: 'Milestones along the way', weight: 2 },
      { label: 'After', description: 'The stunning result', weight: 1.5 },
    ],
    visualStyle: 'mixed-media',
    captionStyle: 'bold-center',
    narrationStyle: 'conversational',
    sceneDuration: { min: 4, max: 10, default: 6 },
    ctaStyles: ['follow', 'save', 'comment'],
    loopStrategy: 'soft-loop',
    musicIntensity: 0.5,
    transitions: ['cut', 'wipe', 'dissolve'],
    audienceTriggers: ['inspiration', 'hope', 'results', 'process'],
  },
  // ─── Education / Knowledge ──────────────────────────────────────────
  {
    id: 'motivation',
    name: 'Motivation',
    category: 'education',
    description: 'High-energy motivational content with powerful quotes, visuals, and calls to action.',
    recommendedDuration: { min: 20, max: 40, default: 30 },
    pacing: 'fast',
    hookStyles: ['bold-claim', 'challenge', 'promise'],
    structure: [
      { label: 'The Fire', description: 'Opening that ignites emotion', weight: 1.5 },
      { label: 'The Truth', description: 'Hard truth or powerful insight', weight: 2 },
      { label: 'The Evidence', description: 'Proof that it works', weight: 2 },
      { label: 'The Call', description: 'Challenge the viewer to act', weight: 2 },
      { label: 'The Push', description: 'Final motivational surge', weight: 1.5 },
    ],
    visualStyle: 'cinematic',
    captionStyle: 'bold-center',
    narrationStyle: 'energetic',
    sceneDuration: { min: 3, max: 10, default: 6 },
    ctaStyles: ['save', 'share', 'follow'],
    loopStrategy: 'soft-loop',
    musicIntensity: 0.8,
    transitions: ['cut', 'flash'],
    audienceTriggers: ['motivation', 'discipline', 'ambition', 'action'],
  },
  {
    id: 'self-improvement',
    name: 'Self-Improvement',
    category: 'education',
    description: 'Practical tips and frameworks for personal growth with actionable advice.',
    recommendedDuration: { min: 25, max: 45, default: 30 },
    pacing: 'moderate',
    hookStyles: ['promise', 'listicle', 'bold-claim'],
    structure: [
      { label: 'The Problem', description: 'What most people get wrong', weight: 1.5 },
      { label: 'The Framework', description: 'The system or principle', weight: 2.5 },
      { label: 'Step 1', description: 'First actionable step', weight: 2 },
      { label: 'Step 2', description: 'Second actionable step', weight: 2 },
      { label: 'The Result', description: 'What changes when you apply this', weight: 1 },
    ],
    visualStyle: 'text-heavy',
    captionStyle: 'phrase',
    narrationStyle: 'educational',
    sceneDuration: { min: 4, max: 10, default: 6 },
    ctaStyles: ['save', 'follow'],
    loopStrategy: 'none',
    musicIntensity: 0.3,
    transitions: ['cut'],
    audienceTriggers: ['growth', 'productivity', 'clarity', 'action'],
  },
  {
    id: 'psychology',
    name: 'Psychology',
    category: 'education',
    description: 'Psychological concepts, biases, and mental models explained with real-world examples.',
    recommendedDuration: { min: 25, max: 45, default: 30 },
    pacing: 'moderate',
    hookStyles: ['curiosity', 'question', 'contrarian'],
    structure: [
      { label: 'The Concept', description: 'Name the psychological phenomenon', weight: 1.5 },
      { label: 'The Example', description: 'Real-world demonstration', weight: 2.5 },
      { label: 'The Science', description: 'Why this happens', weight: 2 },
      { label: 'The Application', description: 'How to use or avoid it', weight: 2 },
    ],
    visualStyle: 'text-heavy',
    captionStyle: 'phrase',
    narrationStyle: 'educational',
    sceneDuration: { min: 5, max: 12, default: 7 },
    ctaStyles: ['save', 'follow'],
    loopStrategy: 'none',
    musicIntensity: 0.3,
    transitions: ['cut', 'dissolve'],
    audienceTriggers: ['curiosity', 'self-knowledge', 'understanding', 'insight'],
  },
  {
    id: 'interesting-facts',
    name: 'Interesting Facts',
    category: 'education',
    description: 'Surprising facts presented in a rapid-fire or deep-dive format.',
    recommendedDuration: { min: 15, max: 30, default: 22 },
    pacing: 'fast',
    hookStyles: ['curiosity', 'statistic', 'shock'],
    structure: [
      { label: 'The Fact', description: 'State the surprising fact', weight: 2 },
      { label: 'The Context', description: 'Why this is surprising', weight: 2 },
      { label: 'The Detail', description: 'Additional layers of information', weight: 2.5 },
      { label: 'The Connection', description: 'How it relates to everyday life', weight: 1.5 },
    ],
    visualStyle: 'mixed-media',
    captionStyle: 'bold-center',
    narrationStyle: 'energetic',
    sceneDuration: { min: 3, max: 8, default: 5 },
    ctaStyles: ['follow', 'share'],
    loopStrategy: 'soft-loop',
    musicIntensity: 0.4,
    transitions: ['cut', 'zoom-cut'],
    audienceTriggers: ['curiosity', 'surprise', 'knowledge', 'amazement'],
  },
  {
    id: 'did-you-know',
    name: 'Did You Know',
    category: 'education',
    description: 'Question-driven format revealing surprising information about familiar topics.',
    recommendedDuration: { min: 15, max: 30, default: 20 },
    pacing: 'fast',
    hookStyles: ['question', 'curiosity', 'statistic'],
    structure: [
      { label: 'The Question', description: 'Did you know that...?', weight: 1.5 },
      { label: 'The Answer', description: 'The surprising revelation', weight: 2 },
      { label: 'The Proof', description: 'Evidence and detail', weight: 2.5 },
      { label: 'The Implication', description: 'Why this matters', weight: 1.5 },
    ],
    visualStyle: 'b-roll',
    captionStyle: 'bold-center',
    narrationStyle: 'conversational',
    sceneDuration: { min: 3, max: 8, default: 5 },
    ctaStyles: ['follow', 'comment'],
    loopStrategy: 'soft-loop',
    musicIntensity: 0.4,
    transitions: ['cut'],
    audienceTriggers: ['curiosity', 'surprise', 'knowledge'],
  },
  {
    id: 'hidden-facts',
    name: 'Hidden Facts',
    category: 'education',
    description: 'Little-known truths about everyday things that change how you see the world.',
    recommendedDuration: { min: 20, max: 35, default: 25 },
    pacing: 'moderate',
    hookStyles: ['curiosity', 'mystery', 'question'],
    structure: [
      { label: 'The Reveal', description: 'Something hidden about the familiar', weight: 2 },
      { label: 'The History', description: 'How this came to be', weight: 2 },
      { label: 'The Evidence', description: 'Proof it is true', weight: 2.5 },
      { label: 'The Impact', description: 'How this changes your view', weight: 1.5 },
    ],
    visualStyle: 'b-roll',
    captionStyle: 'phrase',
    narrationStyle: 'storytelling',
    sceneDuration: { min: 4, max: 10, default: 6 },
    ctaStyles: ['follow', 'share'],
    loopStrategy: 'none',
    musicIntensity: 0.4,
    transitions: ['dissolve', 'cut'],
    audienceTriggers: ['curiosity', 'revelation', 'hidden-knowledge'],
  },
  // ─── History / Science ──────────────────────────────────────────────
  {
    id: 'history',
    name: 'History',
    category: 'education',
    description: 'Historical events and figures presented as engaging narratives with modern relevance.',
    recommendedDuration: { min: 30, max: 45, default: 35 },
    pacing: 'moderate',
    hookStyles: ['story', 'curiosity', 'shock'],
    structure: [
      { label: 'The Hook', description: 'A surprising historical moment', weight: 1.5 },
      { label: 'The Setting', description: 'Time, place, and context', weight: 2 },
      { label: 'The Event', description: 'What happened', weight: 2.5 },
      { label: 'The Impact', description: 'Why it matters today', weight: 2 },
      { label: 'The Connection', description: 'Link to modern life', weight: 1 },
    ],
    visualStyle: 'b-roll',
    captionStyle: 'subtitle',
    narrationStyle: 'storytelling',
    sceneDuration: { min: 5, max: 12, default: 7 },
    ctaStyles: ['follow', 'save'],
    loopStrategy: 'none',
    musicIntensity: 0.4,
    transitions: ['dissolve', 'fade', 'cut'],
    audienceTriggers: ['curiosity', 'knowledge', 'perspective', 'relevance'],
  },
  {
    id: 'history-mysteries',
    name: 'History Mysteries',
    category: 'education',
    description: 'Unsolved historical puzzles and unexplained events presented with evidence and theories.',
    recommendedDuration: { min: 25, max: 45, default: 35 },
    pacing: 'slow',
    hookStyles: ['mystery', 'question', 'curiosity'],
    structure: [
      { label: 'The Mystery', description: 'What remains unexplained', weight: 2 },
      { label: 'The Evidence', description: 'What we do know', weight: 2 },
      { label: 'Theory 1', description: 'Leading explanation', weight: 2 },
      { label: 'Theory 2', description: 'Alternative explanation', weight: 1.5 },
      { label: 'The Question', description: 'Why it is still unsolved', weight: 1.5 },
    ],
    visualStyle: 'cinematic',
    captionStyle: 'subtitle',
    narrationStyle: 'dramatic',
    sceneDuration: { min: 5, max: 12, default: 7 },
    ctaStyles: ['comment', 'follow'],
    loopStrategy: 'none',
    musicIntensity: 0.5,
    transitions: ['fade', 'dissolve', 'cut'],
    audienceTriggers: ['mystery', 'curiosity', 'intrigue', 'wonder'],
  },
  {
    id: 'science-facts',
    name: 'Science Facts',
    category: 'education',
    description: 'Scientific discoveries and phenomena explained accessibly with visual demonstrations.',
    recommendedDuration: { min: 20, max: 40, default: 30 },
    pacing: 'moderate',
    hookStyles: ['curiosity', 'question', 'shock'],
    structure: [
      { label: 'The Discovery', description: 'What scientists found', weight: 2 },
      { label: 'The Experiment', description: 'How they proved it', weight: 2.5 },
      { label: 'The Explanation', description: 'The science behind it', weight: 2 },
      { label: 'The Application', description: 'Why it matters', weight: 1.5 },
    ],
    visualStyle: 'animation',
    captionStyle: 'phrase',
    narrationStyle: 'educational',
    sceneDuration: { min: 5, max: 12, default: 7 },
    ctaStyles: ['save', 'follow'],
    loopStrategy: 'none',
    musicIntensity: 0.3,
    transitions: ['cut', 'dissolve'],
    audienceTriggers: ['curiosity', 'wonder', 'knowledge', 'understanding'],
  },
  {
    id: 'space',
    name: 'Space',
    category: 'education',
    description: 'Cosmic phenomena, space exploration, and astronomical wonders with awe-inspiring visuals.',
    recommendedDuration: { min: 25, max: 45, default: 30 },
    pacing: 'slow',
    hookStyles: ['curiosity', 'shock', 'statistic'],
    structure: [
      { label: 'The Scale', description: 'Start with something mind-blowing about scale', weight: 2 },
      { label: 'The Object', description: 'What we are looking at', weight: 2 },
      { label: 'The Science', description: 'How it works or formed', weight: 2.5 },
      { label: 'The Implication', description: 'What it means for us', weight: 1.5 },
    ],
    visualStyle: 'cinematic',
    captionStyle: 'minimal',
    narrationStyle: 'authoritative',
    sceneDuration: { min: 5, max: 15, default: 8 },
    ctaStyles: ['follow', 'save'],
    loopStrategy: 'soft-loop',
    musicIntensity: 0.5,
    transitions: ['fade', 'dissolve'],
    audienceTriggers: ['awe', 'wonder', 'curiosity', 'existential'],
  },
  // ─── Technology ─────────────────────────────────────────────────────
  {
    id: 'future-predictions',
    name: 'Future / Predictions',
    category: 'technology',
    description: 'Predictions about what is coming next in technology, society, or culture.',
    recommendedDuration: { min: 25, max: 40, default: 30 },
    pacing: 'moderate',
    hookStyles: ['bold-claim', 'curiosity', 'promise'],
    structure: [
      { label: 'The Prediction', description: 'What will happen', weight: 2 },
      { label: 'The Evidence', description: 'Why this is likely', weight: 2.5 },
      { label: 'The Timeline', description: 'When it will happen', weight: 2 },
      { label: 'The Impact', description: 'How it changes everything', weight: 2 },
    ],
    visualStyle: 'ai-generated',
    captionStyle: 'bold-center',
    narrationStyle: 'authoritative',
    sceneDuration: { min: 5, max: 12, default: 7 },
    ctaStyles: ['comment', 'follow'],
    loopStrategy: 'none',
    musicIntensity: 0.5,
    transitions: ['cut', 'glitch'],
    audienceTriggers: ['curiosity', 'excitement', 'fear', 'anticipation'],
  },
  {
    id: 'ai-content',
    name: 'AI Content',
    category: 'technology',
    description: 'Content about artificial intelligence, its capabilities, and its impact on the world.',
    recommendedDuration: { min: 25, max: 45, default: 30 },
    pacing: 'moderate',
    hookStyles: ['shock', 'bold-claim', 'question'],
    structure: [
      { label: 'The Capability', description: 'What AI can now do', weight: 2 },
      { label: 'The Demo', description: 'Show it in action', weight: 2.5 },
      { label: 'The Implication', description: 'What this means for jobs/life', weight: 2 },
      { label: 'The Future', description: 'Where this is heading', weight: 1.5 },
    ],
    visualStyle: 'ai-generated',
    captionStyle: 'bold-center',
    narrationStyle: 'educational',
    sceneDuration: { min: 5, max: 12, default: 7 },
    ctaStyles: ['follow', 'comment', 'share'],
    loopStrategy: 'none',
    musicIntensity: 0.4,
    transitions: ['cut', 'glitch'],
    audienceTriggers: ['curiosity', 'fear', 'excitement', 'understanding'],
  },
  {
    id: 'tech-news',
    name: 'Tech News',
    category: 'technology',
    description: 'Latest technology news and product announcements with analysis and opinion.',
    recommendedDuration: { min: 20, max: 40, default: 30 },
    pacing: 'fast',
    hookStyles: ['bold-claim', 'shock', 'curiosity'],
    structure: [
      { label: 'The News', description: 'What just happened', weight: 2 },
      { label: 'The Context', description: 'Why this matters', weight: 2 },
      { label: 'The Details', description: 'Key specs or features', weight: 2.5 },
      { label: 'The Take', description: 'Our analysis and opinion', weight: 1.5 },
    ],
    visualStyle: 'mixed-media',
    captionStyle: 'phrase',
    narrationStyle: 'energetic',
    sceneDuration: { min: 4, max: 10, default: 7 },
    ctaStyles: ['comment', 'follow'],
    loopStrategy: 'none',
    musicIntensity: 0.4,
    transitions: ['cut'],
    audienceTriggers: ['curiosity', 'relevance', 'opinions', 'fomo'],
  },
  {
    id: 'tech-explainers',
    name: 'Tech Explainers',
    category: 'technology',
    description: 'Complex technology concepts broken down into understandable explanations with visual aids.',
    recommendedDuration: { min: 25, max: 45, default: 35 },
    pacing: 'moderate',
    hookStyles: ['question', 'curiosity', 'promise'],
    structure: [
      { label: 'The Question', description: 'What we are explaining', weight: 1.5 },
      { label: 'The Basics', description: 'Foundation concepts', weight: 2.5 },
      { label: 'The Mechanism', description: 'How it actually works', weight: 2.5 },
      { label: 'The Application', description: 'Real-world use cases', weight: 2 },
    ],
    visualStyle: 'animation',
    captionStyle: 'phrase',
    narrationStyle: 'educational',
    sceneDuration: { min: 5, max: 12, default: 8 },
    ctaStyles: ['save', 'follow'],
    loopStrategy: 'none',
    musicIntensity: 0.3,
    transitions: ['cut', 'dissolve'],
    audienceTriggers: ['understanding', 'curiosity', 'clarity', 'learning'],
  },
  // ─── Business / Finance ─────────────────────────────────────────────
  {
    id: 'money-finance',
    name: 'Money / Finance',
    category: 'business',
    description: 'Personal finance, investing, and money management tips with practical advice.',
    recommendedDuration: { min: 25, max: 45, default: 30 },
    pacing: 'moderate',
    hookStyles: ['bold-claim', 'promise', 'statistic'],
    structure: [
      { label: 'The Money Question', description: 'What people want to know', weight: 1.5 },
      { label: 'The Problem', description: 'Common mistake or misconception', weight: 2 },
      { label: 'The Strategy', description: 'The correct approach', weight: 2.5 },
      { label: 'The Numbers', description: 'Concrete example with figures', weight: 2 },
      { label: 'The Action', description: 'What to do today', weight: 1 },
    ],
    visualStyle: 'text-heavy',
    captionStyle: 'bold-center',
    narrationStyle: 'authoritative',
    sceneDuration: { min: 4, max: 10, default: 6 },
    ctaStyles: ['save', 'follow'],
    loopStrategy: 'none',
    musicIntensity: 0.3,
    transitions: ['cut'],
    audienceTriggers: ['money', 'security', 'growth', 'fear'],
  },
  {
    id: 'business-stories',
    name: 'Business Stories',
    category: 'business',
    description: 'Business narratives about companies, decisions, and outcomes with strategic analysis.',
    recommendedDuration: { min: 30, max: 45, default: 35 },
    pacing: 'moderate',
    hookStyles: ['story', 'shock', 'curiosity'],
    structure: [
      { label: 'The Company', description: 'Who and what they do', weight: 1.5 },
      { label: 'The Decision', description: 'The pivotal business choice', weight: 2 },
      { label: 'The Execution', description: 'How they carried it out', weight: 2.5 },
      { label: 'The Result', description: 'Financial or strategic outcome', weight: 2 },
      { label: 'The Lesson', description: 'What we can learn', weight: 1 },
    ],
    visualStyle: 'b-roll',
    captionStyle: 'phrase',
    narrationStyle: 'storytelling',
    sceneDuration: { min: 5, max: 12, default: 7 },
    ctaStyles: ['follow', 'save'],
    loopStrategy: 'none',
    musicIntensity: 0.4,
    transitions: ['cut', 'dissolve'],
    audienceTriggers: ['business', 'strategy', 'success', 'learning'],
  },
  {
    id: 'startup-stories',
    name: 'Startup Stories',
    category: 'business',
    description: 'Startup journeys from idea to success or failure with founder insights.',
    recommendedDuration: { min: 30, max: 45, default: 35 },
    pacing: 'moderate',
    hookStyles: ['story', 'bold-claim', 'shock'],
    structure: [
      { label: 'The Idea', description: 'How it started', weight: 1.5 },
      { label: 'The Struggle', description: 'Early challenges and pivots', weight: 2.5 },
      { label: 'The Breakthrough', description: 'The moment it clicked', weight: 2 },
      { label: 'The Scale', description: 'Growth and expansion', weight: 2 },
      { label: 'The Today', description: 'Where it is now', weight: 1 },
    ],
    visualStyle: 'mixed-media',
    captionStyle: 'phrase',
    narrationStyle: 'storytelling',
    sceneDuration: { min: 5, max: 10, default: 7 },
    ctaStyles: ['follow', 'comment'],
    loopStrategy: 'none',
    musicIntensity: 0.4,
    transitions: ['cut', 'dissolve'],
    audienceTriggers: ['inspiration', 'entrepreneurship', 'learning', 'ambition'],
  },
  {
    id: 'how-x-makes-money',
    name: 'How X Makes Money',
    category: 'business',
    description: 'Business model breakdowns revealing how companies generate revenue.',
    recommendedDuration: { min: 25, max: 40, default: 30 },
    pacing: 'moderate',
    hookStyles: ['curiosity', 'question', 'statistic'],
    structure: [
      { label: 'The Company', description: 'What they appear to do', weight: 1.5 },
      { label: 'The Surface', description: 'What users see', weight: 1.5 },
      { label: 'The Revenue', description: 'How money actually flows', weight: 3 },
      { label: 'The Scale', description: 'How much they make', weight: 2 },
      { label: 'The Insight', description: 'Why this model works', weight: 1 },
    ],
    visualStyle: 'text-heavy',
    captionStyle: 'bold-center',
    narrationStyle: 'educational',
    sceneDuration: { min: 4, max: 10, default: 6 },
    ctaStyles: ['follow', 'save'],
    loopStrategy: 'none',
    musicIntensity: 0.3,
    transitions: ['cut'],
    audienceTriggers: ['curiosity', 'business', 'money', 'insight'],
  },
  // ─── Food / Travel ──────────────────────────────────────────────────
  {
    id: 'food-content',
    name: 'Food Content',
    category: 'lifestyle',
    description: 'Food-focused content with visual emphasis on preparation, presentation, and taste reactions.',
    recommendedDuration: { min: 15, max: 35, default: 22 },
    pacing: 'moderate',
    hookStyles: ['shock', 'curiosity', 'promise'],
    structure: [
      { label: 'The Dish', description: 'Show the finished product', weight: 1.5 },
      { label: 'The Process', description: 'Key preparation steps', weight: 3 },
      { label: 'The Reveal', description: 'Final presentation', weight: 2 },
      { label: 'The Taste', description: 'Reaction and description', weight: 1.5 },
    ],
    visualStyle: 'cinematic',
    captionStyle: 'minimal',
    narrationStyle: 'casual',
    sceneDuration: { min: 3, max: 8, default: 5 },
    ctaStyles: ['save', 'comment'],
    loopStrategy: 'soft-loop',
    musicIntensity: 0.3,
    transitions: ['cut', 'dissolve'],
    audienceTriggers: ['hunger', 'curiosity', 'satisfaction', 'inspiration'],
  },
  {
    id: 'street-food',
    name: 'Street Food',
    category: 'lifestyle',
    description: 'Street food exploration with cultural context, vendor stories, and food close-ups.',
    recommendedDuration: { min: 20, max: 35, default: 25 },
    pacing: 'moderate',
    hookStyles: ['curiosity', 'shock', 'story'],
    structure: [
      { label: 'The Location', description: 'Where we are', weight: 1.5 },
      { label: 'The Vendor', description: 'Who makes it', weight: 2 },
      { label: 'The Process', description: 'How it is made on the spot', weight: 2.5 },
      { label: 'The Price', description: 'How much it costs', weight: 1 },
      { label: 'The Verdict', description: 'Final taste and rating', weight: 1.5 },
    ],
    visualStyle: 'cinematic',
    captionStyle: 'minimal',
    narrationStyle: 'casual',
    sceneDuration: { min: 3, max: 8, default: 5 },
    ctaStyles: ['follow', 'comment'],
    loopStrategy: 'none',
    musicIntensity: 0.3,
    transitions: ['cut'],
    audienceTriggers: ['travel', 'food', 'culture', 'adventure'],
  },
  {
    id: 'travel',
    name: 'Travel',
    category: 'lifestyle',
    description: 'Travel content showcasing destinations, experiences, and practical travel tips.',
    recommendedDuration: { min: 20, max: 40, default: 28 },
    pacing: 'moderate',
    hookStyles: ['shock', 'promise', 'curiosity'],
    structure: [
      { label: 'The Destination', description: 'Stunning establishing shot', weight: 1.5 },
      { label: 'The Experience', description: 'What you can do there', weight: 2.5 },
      { label: 'The Details', description: 'Practical tips and costs', weight: 2 },
      { label: 'The Feeling', description: 'Why it is worth it', weight: 2 },
    ],
    visualStyle: 'cinematic',
    captionStyle: 'minimal',
    narrationStyle: 'casual',
    sceneDuration: { min: 4, max: 10, default: 7 },
    ctaStyles: ['save', 'follow', 'share'],
    loopStrategy: 'soft-loop',
    musicIntensity: 0.4,
    transitions: ['dissolve', 'cut'],
    audienceTriggers: ['wanderlust', 'adventure', 'escape', 'inspiration'],
  },
  {
    id: 'hidden-places',
    name: 'Hidden Places',
    category: 'lifestyle',
    description: 'Undiscovered or lesser-known locations revealed with insider knowledge.',
    recommendedDuration: { min: 20, max: 35, default: 25 },
    pacing: 'slow',
    hookStyles: ['curiosity', 'mystery', 'promise'],
    structure: [
      { label: 'The Secret', description: 'A place most people do not know', weight: 2 },
      { label: 'The Location', description: 'Where and how to find it', weight: 2 },
      { label: 'The Beauty', description: 'What makes it special', weight: 2.5 },
      { label: 'The Access', description: 'How to visit responsibly', weight: 1.5 },
    ],
    visualStyle: 'cinematic',
    captionStyle: 'minimal',
    narrationStyle: 'conversational',
    sceneDuration: { min: 4, max: 10, default: 6 },
    ctaStyles: ['save', 'follow'],
    loopStrategy: 'none',
    musicIntensity: 0.4,
    transitions: ['dissolve', 'fade'],
    audienceTriggers: ['discovery', 'wanderlust', 'exclusivity', 'wonder'],
  },
  // ─── Gaming ─────────────────────────────────────────────────────────
  {
    id: 'gaming',
    name: 'Gaming',
    category: 'entertainment',
    description: 'Gaming content including gameplay highlights, reviews, and gaming news.',
    recommendedDuration: { min: 20, max: 40, default: 28 },
    pacing: 'fast',
    hookStyles: ['shock', 'bold-claim', 'curiosity'],
    structure: [
      { label: 'The Moment', description: 'Best gameplay moment or news hook', weight: 2 },
      { label: 'The Context', description: 'Game and situation setup', weight: 2 },
      { label: 'The Details', description: 'Mechanics or analysis', weight: 2.5 },
      { label: 'The Verdict', description: 'Opinion or reaction', weight: 1.5 },
    ],
    visualStyle: 'screen-recording',
    captionStyle: 'bold-center',
    narrationStyle: 'energetic',
    sceneDuration: { min: 4, max: 10, default: 7 },
    ctaStyles: ['comment', 'follow'],
    loopStrategy: 'none',
    musicIntensity: 0.5,
    transitions: ['cut', 'glitch'],
    audienceTriggers: ['gaming', 'skill', 'competition', 'nostalgia'],
  },
  {
    id: 'gaming-lore',
    name: 'Gaming Lore',
    category: 'entertainment',
    description: 'Deep dives into game stories, characters, and hidden lore with narrative delivery.',
    recommendedDuration: { min: 30, max: 45, default: 35 },
    pacing: 'moderate',
    hookStyles: ['mystery', 'curiosity', 'story'],
    structure: [
      { label: 'The Mystery', description: 'An unexplained game element', weight: 2 },
      { label: 'The Surface', description: 'What the game shows you', weight: 2 },
      { label: 'The Deep Lore', description: 'Hidden connections and backstory', weight: 2.5 },
      { label: 'The Theory', description: 'What it all means', weight: 1.5 },
    ],
    visualStyle: 'screen-recording',
    captionStyle: 'subtitle',
    narrationStyle: 'storytelling',
    sceneDuration: { min: 5, max: 12, default: 8 },
    ctaStyles: ['comment', 'follow'],
    loopStrategy: 'none',
    musicIntensity: 0.4,
    transitions: ['dissolve', 'cut'],
    audienceTriggers: ['lore', 'mystery', 'nostalgia', 'theory'],
  },
  // ─── Wellness ───────────────────────────────────────────────────────
  {
    id: 'fitness',
    name: 'Fitness',
    category: 'wellness',
    description: 'Exercise routines, fitness tips, and workout demonstrations.',
    recommendedDuration: { min: 20, max: 40, default: 30 },
    pacing: 'fast',
    hookStyles: ['promise', 'challenge', 'bold-claim'],
    structure: [
      { label: 'The Exercise', description: 'Show the movement', weight: 2 },
      { label: 'The Form', description: 'Key technique points', weight: 2.5 },
      { label: 'The Mistake', description: 'Common form error to avoid', weight: 2 },
      { label: 'The Progression', description: 'How to make it harder', weight: 1.5 },
    ],
    visualStyle: 'talking-head',
    captionStyle: 'bold-center',
    narrationStyle: 'energetic',
    sceneDuration: { min: 4, max: 10, default: 7 },
    ctaStyles: ['save', 'follow'],
    loopStrategy: 'soft-loop',
    musicIntensity: 0.6,
    transitions: ['cut'],
    audienceTriggers: ['fitness', 'results', 'challenge', 'discipline'],
  },
  {
    id: 'health-tips',
    name: 'Health Tips',
    category: 'wellness',
    description: 'Evidence-based health advice with practical daily applications.',
    recommendedDuration: { min: 25, max: 40, default: 30 },
    pacing: 'moderate',
    hookStyles: ['bold-claim', 'question', 'promise'],
    structure: [
      { label: 'The Claim', description: 'What the science says', weight: 2 },
      { label: 'The Evidence', description: 'Research or data behind it', weight: 2.5 },
      { label: 'The Method', description: 'How to apply it daily', weight: 2 },
      { label: 'The Result', description: 'Expected outcomes', weight: 1.5 },
    ],
    visualStyle: 'text-heavy',
    captionStyle: 'phrase',
    narrationStyle: 'educational',
    sceneDuration: { min: 5, max: 10, default: 7 },
    ctaStyles: ['save', 'follow'],
    loopStrategy: 'none',
    musicIntensity: 0.3,
    transitions: ['cut'],
    audienceTriggers: ['health', 'wellness', 'improvement', 'knowledge'],
  },
  // ─── Utility / Creative ─────────────────────────────────────────────
  {
    id: 'life-hacks',
    name: 'Life Hacks',
    category: 'lifestyle',
    description: 'Quick practical tips and tricks that solve everyday problems.',
    recommendedDuration: { min: 15, max: 30, default: 20 },
    pacing: 'fast',
    hookStyles: ['promise', 'curiosity', 'challenge'],
    structure: [
      { label: 'The Problem', description: 'Common annoyance', weight: 1.5 },
      { label: 'The Hack', description: 'The clever solution', weight: 2.5 },
      { label: 'The Demo', description: 'Show it working', weight: 2 },
      { label: 'The Bonus', description: 'Additional tip or variation', weight: 1 },
    ],
    visualStyle: 'mixed-media',
    captionStyle: 'bold-center',
    narrationStyle: 'casual',
    sceneDuration: { min: 3, max: 8, default: 5 },
    ctaStyles: ['save', 'share', 'follow'],
    loopStrategy: 'soft-loop',
    musicIntensity: 0.4,
    transitions: ['cut', 'whip-pan'],
    audienceTriggers: ['utility', 'satisfaction', 'curiosity', 'savings'],
  },
  {
    id: 'tutorials',
    name: 'Tutorials',
    category: 'education',
    description: 'Step-by-step instructional content teaching a specific skill.',
    recommendedDuration: { min: 30, max: 45, default: 35 },
    pacing: 'slow',
    hookStyles: ['promise', 'question', 'bold-claim'],
    structure: [
      { label: 'The Goal', description: 'What you will learn to do', weight: 1.5 },
      { label: 'The Setup', description: 'What you need', weight: 1.5 },
      { label: 'Step 1', description: 'First step with detail', weight: 2 },
      { label: 'Step 2', description: 'Second step with detail', weight: 2 },
      { label: 'Step 3', description: 'Third step with detail', weight: 2 },
      { label: 'The Result', description: 'Finished product', weight: 1 },
    ],
    visualStyle: 'screen-recording',
    captionStyle: 'phrase',
    narrationStyle: 'educational',
    sceneDuration: { min: 4, max: 12, default: 6 },
    ctaStyles: ['save', 'follow'],
    loopStrategy: 'none',
    musicIntensity: 0.2,
    transitions: ['cut'],
    audienceTriggers: ['learning', 'skill', 'clarity', 'achievement'],
  },
  {
    id: 'product-discovery',
    name: 'Product Discovery',
    category: 'lifestyle',
    description: 'Product recommendations and finds with honest reviews and use cases.',
    recommendedDuration: { min: 20, max: 35, default: 25 },
    pacing: 'moderate',
    hookStyles: ['promise', 'bold-claim', 'shock'],
    structure: [
      { label: 'The Product', description: 'What it is', weight: 1.5 },
      { label: 'The Problem', description: 'What it solves', weight: 2 },
      { label: 'The Experience', description: 'Using it in practice', weight: 2.5 },
      { label: 'The Verdict', description: 'Worth it or not', weight: 2 },
    ],
    visualStyle: 'mixed-media',
    captionStyle: 'phrase',
    narrationStyle: 'conversational',
    sceneDuration: { min: 4, max: 10, default: 6 },
    ctaStyles: ['save', 'comment', 'follow'],
    loopStrategy: 'none',
    musicIntensity: 0.3,
    transitions: ['cut'],
    audienceTriggers: ['discovery', 'value', 'trust', 'recommendation'],
  },
  {
    id: 'product-testing',
    name: 'Product Testing',
    category: 'lifestyle',
    description: 'Hands-on product tests comparing claims to reality with visual evidence.',
    recommendedDuration: { min: 25, max: 40, default: 30 },
    pacing: 'moderate',
    hookStyles: ['challenge', 'question', 'bold-claim'],
    structure: [
      { label: 'The Claim', description: 'What the product promises', weight: 2 },
      { label: 'The Test', description: 'How we test it', weight: 2.5 },
      { label: 'The Result', description: 'Does it work?', weight: 2 },
      { label: 'The Verdict', description: 'Buy or skip', weight: 1.5 },
    ],
    visualStyle: 'mixed-media',
    captionStyle: 'bold-center',
    narrationStyle: 'casual',
    sceneDuration: { min: 5, max: 10, default: 7 },
    ctaStyles: ['comment', 'save'],
    loopStrategy: 'none',
    musicIntensity: 0.3,
    transitions: ['cut'],
    audienceTriggers: ['curiosity', 'trust', 'value', 'honesty'],
  },
  // ─── Satisfying / Visual ────────────────────────────────────────────
  {
    id: 'satisfying-videos',
    name: 'Satisfying Videos',
    category: 'entertainment',
    description: 'Visually or audibly satisfying content with mesmerizing patterns and completion.',
    recommendedDuration: { min: 15, max: 30, default: 20 },
    pacing: 'slow',
    hookStyles: ['curiosity', 'promise'],
    structure: [
      { label: 'The Setup', description: 'Initial state before satisfaction', weight: 1.5 },
      { label: 'The Process', description: 'The satisfying action in progress', weight: 3 },
      { label: 'The Completion', description: 'The finished satisfying result', weight: 2.5 },
    ],
    visualStyle: 'cinematic',
    captionStyle: 'minimal',
    narrationStyle: 'casual',
    sceneDuration: { min: 5, max: 15, default: 7 },
    ctaStyles: ['follow', 'share'],
    loopStrategy: 'hard-loop',
    musicIntensity: 0.2,
    transitions: ['cut', 'dissolve'],
    audienceTriggers: ['satisfaction', 'calm', 'mesmerized', 'completion'],
  },
  {
    id: 'asmr',
    name: 'ASMR',
    category: 'entertainment',
    description: 'ASMR-triggering content with careful audio, close-ups, and gentle pacing.',
    recommendedDuration: { min: 20, max: 40, default: 30 },
    pacing: 'slow',
    hookStyles: ['promise', 'curiosity'],
    structure: [
      { label: 'The Trigger', description: 'Introduce the ASMR trigger', weight: 2 },
      { label: 'The Build', description: 'Gradual intensification', weight: 2.5 },
      { label: 'The Peak', description: 'Maximum trigger intensity', weight: 2.5 },
      { label: 'The Release', description: 'Gentle wind-down', weight: 1 },
    ],
    visualStyle: 'cinematic',
    captionStyle: 'minimal',
    narrationStyle: 'whisper',
    sceneDuration: { min: 5, max: 15, default: 8 },
    ctaStyles: ['follow', 'save'],
    loopStrategy: 'soft-loop',
    musicIntensity: 0.1,
    transitions: ['fade', 'dissolve'],
    audienceTriggers: ['relaxation', 'tingles', 'calm', 'focus'],
  },
  {
    id: 'oddly-satisfying',
    name: 'Oddly Satisfying',
    category: 'entertainment',
    description: 'Content that triggers satisfaction through perfect fits, clean processes, or symmetry.',
    recommendedDuration: { min: 15, max: 25, default: 18 },
    pacing: 'slow',
    hookStyles: ['curiosity', 'promise'],
    structure: [
      { label: 'The Imperfect', description: 'Show what needs fixing/completing', weight: 2 },
      { label: 'The Process', description: 'The satisfying transformation', weight: 3 },
      { label: 'The Perfect', description: 'The clean, satisfying result', weight: 2.5 },
    ],
    visualStyle: 'cinematic',
    captionStyle: 'minimal',
    narrationStyle: 'casual',
    sceneDuration: { min: 4, max: 10, default: 6 },
    ctaStyles: ['follow', 'share'],
    loopStrategy: 'hard-loop',
    musicIntensity: 0.15,
    transitions: ['cut', 'dissolve'],
    audienceTriggers: ['satisfaction', 'perfection', 'calm', 'order'],
  },
  {
    id: 'ai-visual-stories',
    name: 'AI Visual Stories',
    category: 'creative',
    description: 'Narratives told through AI-generated visuals with creative transitions and surreal imagery.',
    recommendedDuration: { min: 20, max: 40, default: 28 },
    pacing: 'moderate',
    hookStyles: ['shock', 'curiosity', 'mystery'],
    structure: [
      { label: 'The Vision', description: 'Opening AI-generated image/scene', weight: 2 },
      { label: 'The Narrative', description: 'Story unfolds through visuals', weight: 2.5 },
      { label: 'The Escalation', description: 'Surreal or dramatic turn', weight: 2 },
      { label: 'The Resolution', description: 'Final visual payoff', weight: 1.5 },
    ],
    visualStyle: 'ai-generated',
    captionStyle: 'subtitle',
    narrationStyle: 'dramatic',
    sceneDuration: { min: 4, max: 10, default: 7 },
    ctaStyles: ['follow', 'comment'],
    loopStrategy: 'soft-loop',
    musicIntensity: 0.6,
    transitions: ['dissolve', 'morph', 'fade'],
    audienceTriggers: ['wonder', 'curiosity', 'creativity', 'surreal'],
  },
  {
    id: 'mini-documentaries',
    name: 'Mini Documentaries',
    category: 'creative',
    description: 'Short documentary-style content with evidence, expert analysis, and compelling narratives.',
    recommendedDuration: { min: 35, max: 45, default: 40 },
    pacing: 'moderate',
    hookStyles: ['curiosity', 'story', 'question'],
    structure: [
      { label: 'Hook', description: 'Compelling opening question or statement', weight: 1.5 },
      { label: 'Context', description: 'Background and stakes', weight: 2 },
      { label: 'Evidence', description: 'Facts, data, expert input', weight: 2.5 },
      { label: 'Explanation', description: 'What it all means', weight: 2 },
      { label: 'Visual Proof', description: 'Supporting imagery or footage', weight: 1.5 },
      { label: 'Conclusion', description: 'Summary and call to think deeper', weight: 1.5 },
    ],
    visualStyle: 'b-roll',
    captionStyle: 'subtitle',
    narrationStyle: 'authoritative',
    sceneDuration: { min: 5, max: 12, default: 7 },
    ctaStyles: ['follow', 'save', 'share'],
    loopStrategy: 'none',
    musicIntensity: 0.4,
    transitions: ['dissolve', 'fade', 'cut'],
    audienceTriggers: ['curiosity', 'understanding', 'depth', 'truth'],
  },
] as const;

/** Lookup map for quick format access by id. */
export const CONTENT_FORMAT_MAP: ReadonlyMap<string, ContentFormatRecipe> = new Map(
  CONTENT_FORMATS.map((f) => [f.id, f]),
);

/** All format ids. */
export const CONTENT_FORMAT_IDS: readonly string[] = CONTENT_FORMATS.map((f) => f.id);

/** All format names for display. */
export const CONTENT_FORMAT_LABELS: Readonly<Record<string, string>> = Object.fromEntries(
  CONTENT_FORMATS.map((f) => [f.id, f.name]),
);

/** Formats grouped by category. */
export const CONTENT_FORMATS_BY_CATEGORY: Readonly<Record<string, readonly ContentFormatRecipe[]>> =
  Object.fromEntries(
    Array.from(new Set(CONTENT_FORMATS.map((f) => f.category))).map((cat) => [
      cat,
      CONTENT_FORMATS.filter((f) => f.category === cat),
    ]),
  );
